use super::types::{
    AssistantToolSpec, ToolAccessMode, ToolConfirmationPolicy, ToolRiskTier, ToolRoleRequirement,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AssistantToolName {
    AccountGetProfileSummary,
    CalendarListEvents,
    CalendarUpcomingBirthdays,
    DownloadsListAvailableArtifacts,
    LibrariesListAccessible,
    LibrarySearchTitles,
    LibraryGetItemSummary,
    WebSearchPublicWeb,
    WebFetchPublicPageSummary,
    RoomsListActive,
    RoomsGetRoomSummary,
    SystemGetHostRuntimeSummary,
    ServersListMinecraftStatus,
    ServersGetMinecraftServerSummary,
}

impl AssistantToolName {
    pub const fn all() -> &'static [Self] {
        &[
            Self::AccountGetProfileSummary,
            Self::CalendarListEvents,
            Self::CalendarUpcomingBirthdays,
            Self::DownloadsListAvailableArtifacts,
            Self::LibrariesListAccessible,
            Self::LibrarySearchTitles,
            Self::LibraryGetItemSummary,
            Self::WebSearchPublicWeb,
            Self::WebFetchPublicPageSummary,
            Self::RoomsListActive,
            Self::RoomsGetRoomSummary,
            Self::SystemGetHostRuntimeSummary,
            Self::ServersListMinecraftStatus,
            Self::ServersGetMinecraftServerSummary,
        ]
    }

    pub fn from_str(value: &str) -> Option<Self> {
        match value {
            "account_get_profile_summary" => Some(Self::AccountGetProfileSummary),
            "calendar_list_events" => Some(Self::CalendarListEvents),
            "calendar_upcoming_birthdays" => Some(Self::CalendarUpcomingBirthdays),
            "downloads_list_available_artifacts" => Some(Self::DownloadsListAvailableArtifacts),
            "libraries_list_accessible" => Some(Self::LibrariesListAccessible),
            "library_search_titles" => Some(Self::LibrarySearchTitles),
            "library_get_item_summary" => Some(Self::LibraryGetItemSummary),
            "web_search_public_web" => Some(Self::WebSearchPublicWeb),
            "web_fetch_public_page_summary" => Some(Self::WebFetchPublicPageSummary),
            "rooms_list_active" => Some(Self::RoomsListActive),
            "rooms_get_room_summary" => Some(Self::RoomsGetRoomSummary),
            "system_get_host_runtime_summary" => Some(Self::SystemGetHostRuntimeSummary),
            "servers_list_minecraft_status" => Some(Self::ServersListMinecraftStatus),
            "servers_get_minecraft_server_summary" => Some(Self::ServersGetMinecraftServerSummary),
            _ => None,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AccountGetProfileSummary => "account_get_profile_summary",
            Self::CalendarListEvents => "calendar_list_events",
            Self::CalendarUpcomingBirthdays => "calendar_upcoming_birthdays",
            Self::DownloadsListAvailableArtifacts => "downloads_list_available_artifacts",
            Self::LibrariesListAccessible => "libraries_list_accessible",
            Self::LibrarySearchTitles => "library_search_titles",
            Self::LibraryGetItemSummary => "library_get_item_summary",
            Self::WebSearchPublicWeb => "web_search_public_web",
            Self::WebFetchPublicPageSummary => "web_fetch_public_page_summary",
            Self::RoomsListActive => "rooms_list_active",
            Self::RoomsGetRoomSummary => "rooms_get_room_summary",
            Self::SystemGetHostRuntimeSummary => "system_get_host_runtime_summary",
            Self::ServersListMinecraftStatus => "servers_list_minecraft_status",
            Self::ServersGetMinecraftServerSummary => "servers_get_minecraft_server_summary",
        }
    }

    pub const fn spec(self) -> AssistantToolSpec {
        match self {
            Self::AccountGetProfileSummary => AssistantToolSpec {
                name: "account_get_profile_summary",
                summary: "Summarize the signed-in Rustyfin account and access scope.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 2_000,
                max_result_bytes: 4 * 1024,
            },
            Self::CalendarListEvents => AssistantToolSpec {
                name: "calendar_list_events",
                summary: "List visible upcoming calendar events for a short time window.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 3_000,
                max_result_bytes: 8 * 1024,
            },
            Self::CalendarUpcomingBirthdays => AssistantToolSpec {
                name: "calendar_upcoming_birthdays",
                summary: "List visible upcoming birthdays from calendar data.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 3_000,
                max_result_bytes: 8 * 1024,
            },
            Self::DownloadsListAvailableArtifacts => AssistantToolSpec {
                name: "downloads_list_available_artifacts",
                summary: "List authenticated host-published Rustyfin downloads and planned artifacts.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 2_000,
                max_result_bytes: 8 * 1024,
            },
            Self::LibrariesListAccessible => AssistantToolSpec {
                name: "libraries_list_accessible",
                summary: "List libraries the current user can access.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 3_000,
                max_result_bytes: 8 * 1024,
            },
            Self::LibrarySearchTitles => AssistantToolSpec {
                name: "library_search_titles",
                summary: "Search accessible library item titles for a user-provided query.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 4_000,
                max_result_bytes: 8 * 1024,
            },
            Self::LibraryGetItemSummary => AssistantToolSpec {
                name: "library_get_item_summary",
                summary: "Load a tighter summary for one accessible library item.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 4_000,
                max_result_bytes: 8 * 1024,
            },
            Self::WebSearchPublicWeb => AssistantToolSpec {
                name: "web_search_public_web",
                summary: "Search a constrained public web source for current public information.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Moderate,
                required_role: ToolRoleRequirement::AdminOnly,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 6_000,
                max_result_bytes: 8 * 1024,
            },
            Self::WebFetchPublicPageSummary => AssistantToolSpec {
                name: "web_fetch_public_page_summary",
                summary: "Fetch and summarize one constrained public web page.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Moderate,
                required_role: ToolRoleRequirement::AdminOnly,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 6_000,
                max_result_bytes: 8 * 1024,
            },
            Self::RoomsListActive => AssistantToolSpec {
                name: "rooms_list_active",
                summary: "List currently active public rooms that the user can see.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 2_000,
                max_result_bytes: 8 * 1024,
            },
            Self::RoomsGetRoomSummary => AssistantToolSpec {
                name: "rooms_get_room_summary",
                summary: "Load a tighter summary for one active public room.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Low,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 3_000,
                max_result_bytes: 8 * 1024,
            },
            Self::SystemGetHostRuntimeSummary => AssistantToolSpec {
                name: "system_get_host_runtime_summary",
                summary: "Summarize current Rustyfin host CPU, memory, load, and runtime counters.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Moderate,
                required_role: ToolRoleRequirement::AdminOnly,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 4_000,
                max_result_bytes: 8 * 1024,
            },
            Self::ServersListMinecraftStatus => AssistantToolSpec {
                name: "servers_list_minecraft_status",
                summary: "List accessible Minecraft server status summaries.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Moderate,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 3_000,
                max_result_bytes: 8 * 1024,
            },
            Self::ServersGetMinecraftServerSummary => AssistantToolSpec {
                name: "servers_get_minecraft_server_summary",
                summary: "Load a tighter summary for one accessible Minecraft server.",
                access_mode: ToolAccessMode::ReadOnly,
                risk_tier: ToolRiskTier::Moderate,
                required_role: ToolRoleRequirement::AnyAuthenticatedUser,
                confirmation: ToolConfirmationPolicy::None,
                timeout_ms: 4_000,
                max_result_bytes: 8 * 1024,
            },
        }
    }
}
