#![allow(
    clippy::collapsible_if,
    clippy::ptr_arg,
    clippy::should_implement_trait
)]
pub mod account_backups;
pub mod account_prefs;
pub mod ai;
pub mod ai_admin;
#[cfg(feature = "ai")]
pub mod ai_assistant;
pub mod ai_audit;
#[cfg(feature = "ai")]
pub mod ai_benchmark;
#[cfg(feature = "ai")]
pub mod ai_benchmark_recommendations;
#[cfg(feature = "ai")]
pub mod ai_conversations;
#[cfg(feature = "ai")]
pub mod ai_enabled;
#[cfg(feature = "ai")]
pub mod ai_eval_harness;
#[cfg(feature = "ai")]
pub mod ai_generated_artifacts;
#[cfg(feature = "ai")]
pub mod ai_model_routing;
pub mod ai_role_routing;
#[cfg(feature = "ai")]
pub mod ai_runtime;
pub mod ai_storage;
#[cfg(feature = "ai")]
pub mod ai_tasks;
pub mod ai_transcribe;
#[cfg(feature = "ai")]
pub mod ai_turn_journal;
pub mod artwork;
pub mod audit_log;
pub mod auth;
pub mod backups;
pub mod channels;
pub mod dictionary;
pub mod dictionary_hardening_helpers;
pub mod downloads;
pub mod error;
pub mod host_directories;
pub mod job_status;
pub mod library_scan;
pub mod network_diagnostics;
pub mod routes;
pub mod runtime_diagnostics;
pub mod runtime_metrics;
#[cfg(feature = "rustyvault")]
pub mod rustyvault_host;
pub mod servers;
pub mod setup;
pub mod smart_home;
pub mod state;
pub mod streaming;
pub mod tmdb_sync;
pub mod transcription_agent;
pub mod user_activity;
pub mod user_pipeline;
pub mod watch_party;
